# Database settings
database:
  host: "95.217.194.15"
  port: 27017

# General pickaxe menu settings
pickaxe-menu:
  name: "&d&lUpgrade menu"
  slots: 45
  filler:
    name: " "
    lore:
      - " "
    material: "GRAY_STAINED_GLASS_PANE"
  gembank:
    material: "SUNFLOWER"
    name: "&d&lGemBank"
    slot: 36
    lore:
      - "&7Click to open the gembank."
  settings:
    material: "REDSTONE_TORCH"
    name: "&c&lSettings"
    slot: 44
    lore:
      - "&7Click to open the settings menu."

gembank:
  filler:
    name: " "
    lore:
      - " "
    material: "GRAY_STAINED_GLASS_PANE"
  main-menu:
    name: "&d&lGemBank"
    slots: 27
    info:
      material: "SUNFLOWER"
      name: "&d&lGems"
      slot: 13
      lore:
        - "&7You currently have"
        - "&d%gems% &7gems deposited"
        - ""
        - "&d&lInterest"
        - "&7Every 24 hours, you will get &d1%"
        - "&7interest on the deposited gems"
        - "&7that are in your account"
    withdraw:
      material: "PAPER"
      name: "&c&lWithdraw gems"
      slot: 15
      lore:
        - "&7Click to withdraw gems"
        - "&7out of your account"
    deposit:
      material: "PAPER"
      name: "&a&lDeposit gems"
      slot: 11
      lore:
        - "&7Click to deposit gems"
        - "&7into your account"
    close:
      material: "BARRIER"
      name: "&c&lClose"
      slot: 22
      lore:
        - ""
  withdraw-menu:
    name: "&c&lWithdraw Gems"
    slots: 27
    1:
      material: "SUNFLOWER"
      amount: 1
      name: "&c&lWithdraw 1x gem"
      slot: 11
      lore:
        - "&7Click to withdraw"
        - "&c1 &7Gem"
    10:
      material: "SUNFLOWER"
      amount: 10
      name: "&c&lWithdraw 10x gems"
      slot: 13
      lore:
        - "&7Click to withdraw"
        - "&c10 &7Gems"
    all:
      material: "SUNFLOWER"
      amount: 64
      name: "&c&lWithdraw all gems"
      slot: 15
      lore:
        - "&7Click to withdraw"
        - "&7all the gems"
        - "&7that are in your account"
    back:
      material: "BARRIER"
      name: "&c&lBack"
      slot: 22
      lore:
        - "&7Click to go back to"
        - "&7the gem bank"
  deposit-menu:
    name: "&a&lDeposit Gems"
    slots: 27
    1:
      material: "SUNFLOWER"
      amount: 1
      name: "&a&lDeposit 1x gem"
      slot: 11
      lore:
        - "&7Click to deposit"
        - "&a1 &7Gem"
    10:
      material: "SUNFLOWER"
      amount: 10
      name: "&a&lDeposit 10x gems"
      slot: 13
      lore:
        - "&7Click to deposit"
        - "&a10 &7Gems"
    all:
      material: "SUNFLOWER"
      amount: 64
      name: "&a&lDeposit all gems"
      slot: 15
      lore:
        - "&7Click to deposit"
        - "&7all the gems"
        - "&7that are in your inventory"
    back:
      material: "BARRIER"
      name: "&c&lBack"
      slot: 22
      lore:
        - "&7Click to go back to"
        - "&7the gem bank"

minebomb:
  name: "&d&lMineBomb"
  lore:
    - "&7Drop in mine"
    - "&7to boom."

# Pickaxe menu enchantment settings
enchants:
  autoblock:
    refundable: true
    name: "&a&lAutoBlock"
    lore:
      - "&8» &7Automatically creates"
      - "&8» &7blocks from ingots."
      - ""
      - "&aCurrent state:"
      - "&8» &7%state%"
      - ""
      - "&aPrice: &7250 gems"
      - ""
      - "&c&lNote: &r&cyou must have the"
      - "&cAutoSmelt enchantment in order"
      - "&cfor this enchantment to work."
    slot: 21
    material: IRON_BLOCK
    price: 10
    max-level: 1
  autodeposit:
    refundable: true
    name: "&e&lAutoDeposit"
    lore:
      - ""
      - "&8» &7Automatically deposits"
      - "&8» &7your gems into"
      - "&8» &7your bank account."
      - ""
      - "&eCurrent state: "
      - "&8» &7%state%"
      - ""
      - "&c&lNote: &r&cyou must have the"
      - "&cGemChance enchantment in order"
      - "&cfor this enchantment to work."
    slot: 13
    material: HOPPER_MINECART
    price: 10
    max-level: 1
  autominer:
    refundable: true
    name: "&a&lAutoMiner"
    lore:
      - "&8» &7Automatically makes you money"
      - "&8» &7with the fortune level on your pickaxe."
      - "&8» &7Go to /warp autominer to start!"
      - ""
      - "&aCurrent state:"
      - "&8» &7%state%"
      - ""
      - "&aPrice: &71000 gems"
    slot: 40
    material: STONECUTTER
    price: 10
    max-level: 1
  autosell:
    refundable: true
    name: "&a&lAutoSell"
    lore:
      - "&8» &7Automatically sells"
      - "&8» &7your inventory when"
      - "&8» &7it's full."
      - ""
      - "&aCurrent state:"
      - "&8» &7%state%"
      - ""
      - "&aPrice: &7500 gems"
    slot: 24
    material: PAPER
    price: 10
    max-level: 1
  autosmelt:
    refundable: true
    name: "&9&lAutoSmelt"
    lore:
      - "&8» &7Automatically smelts"
      - "&8» &7ores into ingots."
      - ""
      - "&9Current state:"
      - "&8» &7%state%"
      - ""
      - "&9Price: &7150 gems"
    slot: 23
    material: BLAST_FURNACE
    price: 10
    max-level: 1
  explosive:
    refundable: true
    name: "&c&lExplosive"
    lore:
      - "&8» &7Gives a chance of"
      - "&8» &7creating an explosion at"
      - "&8» &7the broken block."
      - ""
      - "&cCurrent level:"
      - "&8» &7%level%"
      - ""
      - "&cCurrent chance: "
      - "&8» &7%chance%%"
      - ""
      - "&cPrice: &7%price%"
    slot: 31
    material: TNT
    chance: 0.005
    price: 10
    increase: 5
    max-level: 100
  flight:
    refundable: true
    name: "&b&lFlight"
    lore:
      - "&8» &7Gives infinite"
      - "&8» &7flight while holding"
      - "&8» &7your pickaxe."
      - ""
      - "&bCurrent state:"
      - "&8» &7%state%"
      - ""
      - "&bPrice: &7250 gems"
    slot: 32
    material: ELYTRA
    price: 10
    max-level: 1
  gemchance:
    refundable: true
    name: "&d&lGemChance"
    lore:
      - "&8» &7Increases the chance"
      - "&8» &7of receiving a Gem while"
      - "&8» &7mining."
      - ""
      - "&dCurrent level:"
      - "&8» &7%level%"
      - ""
      - "&dCurrent chance: "
      - "&8» &7%chance%%"
      - ""
      - "&dPrice: &7%price%"
    slot: 22
    material: SUNFLOWER
    chance: 0.005
    price: 10
    increase: 5
    max-level: 100
    gem:
      material: SUNFLOWER
      name: "&d&lGem"
      lore:
        - "&8» &7You can use Gems to"
        - "&8» &7buy special in-game items at"
        - "&8» &7/shop or by right-clicking"
        - "&8» &7your pickaxe"
  haste:
    refundable: true
    name: "Haste"
    lore:
      - "lore1"
      - "lore2"
      - ""
      - "&6Current level: "
      - "&8» &7%level%"
      - ""
      - "&6Current chance: "
      - "&8» &7%chance%%"
      - ""
      - "&6Price: &7%price%"
    slot: 0
    material: GOLDEN_PICKAXE
    chance: 0.005
    price: 10
    increase: 5
    max-level: 2
  jackhammer:
    refundable: true
    name: "&b&lJackHammer"
    lore:
      - "&8» &7Gives a small chance to"
      - "&8» &7remove a complete horizontal layer"
      - "&8» &7from a mine."
      - " "
      - "&bCurrent level: "
      - "&8» &7%level%"
      - " "
      - "&bCurrent chance: "
      - "&8» &7%chance%%"
      - " "
      - "&bPrice: &7%price%"
    slot: 12
    material: DIAMOND_PICKAXE
    chance: 0.005
    price: 10
    increase: 5
    max-level: 100
  jump:
    refundable: true
    name: "Jump"
    lore:
      - "lore1"
      - "lore2"
      - ""
      - "&6Current level: "
      - "&8» &7%level%"
      - ""
      - "&6Current chance: "
      - "&8» &7%chance%%"
      - ""
      - "&6Price: &7%price%"
    slot: 1
    material: RABBIT_FOOT
    chance: 0.005
    price: 10
    increase: 5
    max-level: 100
  keyfinder:
    refundable: true
    name: "&d&lKeyfinder"
    lore:
      - "&8» &7Increases the chance"
      - "&8» &7of receiving a crate key"
      - "&8» &7while mining."
      - ""
      - "&dCurrent level:"
      - "&8» &7%level%"
      - ""
      - "&dCurrent chance: "
      - "&8» &7%chance%%"
      - ""
      - "&dPrice: &7%price%"
    slot: 14
    material: TRIPWIRE_HOOK
    chance: 0.005
    price: 10
    increase: 5
    max-level: 100
    commands:
      - "cc give p Factory 1 %player% ; 0.05"
      - "cc give p Factory 1 %player% ; 0.1"
      - "cc give p Factory 1 %player% ; 0.5"
  laser:
    refundable: true
    name: "&6&lLaser"
    lore:
      - "&8» &7Gives a small chance to"
      - "&8» &7remove a complete vertical layer"
      - "&8» &7from a mine."
      - ""
      - "&6Current level: "
      - "&8» &7%level%"
      - ""
      - "&6Current chance: "
      - "&8» &7%chance%%"
      - ""
      - "&6Price: &7%price%"
    slot: 4
    material: BLAZE_ROD
    chance: 0.005
    price: 10
    increase: 5
    max-level: 100
  lightning:
    refundable: true
    name: "Lightning"
    lore:
      - "lore1"
      - "lore2"
      - ""
      - "&6Current level: "
      - "&8» &7%level%"
      - ""
      - "&6Current chance: "
      - "&8» &7%chance%%"
      - ""
      - "&6Price: &7%price%"
    slot: 2
    material: BONE
    chance: 0.005
    price: 10
    increase: 5
    max-level: 100
  speed:
    refundable: true
    name: "&9&lWalking Speed"
    lore:
      - "&8» &7Gives infinite"
      - "&8» &7walking speed while"
      - "&8» &7holding your pickaxe."
      - ""
      - "&9Current percentage:"
      - "&8» &7%percentage%"
      - ""
      - "&9Price: &7%price%"
    slot: 30
    material: FEATHER
    chance: 0.005
    price: 10
    increase: 5
    max-level: 10
  telepathy:
    refundable: true
    name: "&bTelepathy"
    lore:
      - "&8» &7Automatically puts"
      - "&8» &7broken blocks"
      - "&8» &7in your inventory."
      - ""
      - "&bCurrent state:"
      - "&8» &7%state%"
      - ""
      - "&bPrice: &7250 gems"
    slot: 20
    material: ENDER_PEARL
    price: 10
    max-level: 1
messages:
#  General
  invalid-permission: "&cInvalid permissions!"
  invalid-sender: "&cYou cannot execute this command via the console!"
  invalid-target: "&cPlayer &l%player% &cnot found!"
  invalid-number: "&c&l%arg% &cis not a valid number!"
  incuffient-funds: "&cYou do not have enough tokens!"
  inventory-full: "&c&lInventory Full"

#  Usage
  gems-usage:
    - "&e&l------------- &dLevel &ePickaxe &dUsage &e&l-------------"
    - "&8» &7/gems"
    - "&8» &7/gems add <player> <gems>"
    - "&8» &7/gems give <player> <gems>"
    - "&8» &7/gems remove <player> <gems>"
    - "&8» &7/gems set <player> <gems>"
  pickaxe-usage:
    - "&e&l------------- &bGems &bUsage &e&l-------------"
    - "&8» &7/levelpickaxe give <player>"
    - "&8» &7/levelpickaxe setlevel <player> <level>"
    - "&8» &7/levelpickaxe setblocks <player> <blocks>"
    - "&8» &7/levelpickaxe setexp <player> <exp>"
  set-gems-usage: "&cUsage: /gems set <player> <amount>"
  add-gems-usage: "&cUsage: /gems add <player> <amount>"
  remove-gems-usage: "&cUsage: /gems remove <player> <amount>"
  give-gems-usage: "&cUsage: /gems give <player> <amount>"

  give-pickaxe-usage: "&cUsage: /levelpick give <player>"
  set-blocks-usage: "&cUsage: /levelpick setblocks <player> <blocks>"
  set-level-usage: "&cUsage: /levelpick setlevel <player> <level>"
  set-exp-usage: "&cUsage: /levelpick setexp <player> <level>"
  reset-pickaxe-usage: "&cUsage: /levelpick reset <player>!"

  give-minebomb-usage: "&cUsage: /givebomb <player> <amount>"

#  Gems
  gems: "&8» &7You currently have &d%gems% &7gems!"
  set-gems: "&8» &7Your gems have been set to &d%gems%&7!"
  set-gems-sender: "&8» &7Set gems of %target% to &d%gems%&7!"
  add-gems: "&d%gems% &7gems have been added to your account!"
  add-gems-sender: "&8» &7Added &d%gems%&7 to the account of %target%!"
  remove-gems: "&d%gems% &7gems have been removed to your account!"
  remove-gems-sender: "&8» &7Removed &d%gems% &7gems from the account of %target%!"
  give-gems: "&8» &7You have given %target% &d%gems% &7gems!"
  receive-gems: "&8» &7You have received &d%gems% &7gems from %sender%!"
  gem-chance: "&8» &7You found &d1x Gem &7while mining!"
  interest: "&8» &7Interest time! You got &d%gems% &7gem(s), your new balance is &d%balance% &7!"

#  Pickaxe
  give-pickaxe: "&8» &7You have given %target% a level pickaxe!"
  receive-pickaxe: "&8» &7You have received a level pickaxe!"
  reset-pickaxe: "&8» &7Your level pickaxe has been reset!"
  reset-pickaxe-sender: "&8» &7You have reset %target%'s level pickaxe!"
  set-level: "&8» &7The level of your pickaxe has been set to &d%level%&7!"
  set-level-sender: "&8» &7Set level of %target%'s pickaxe to &d%level%&7!"
  set-blocks: "&8» &7The amount of broken blocks of your pickaxe has been set to &d%blocks%&7!"
  set-blocks-sender: "&8» &7Set broken blocks of %target%'s pickaxe to &d%blocks%&7!"
  set-exp: "&8» &7The exp of your pickaxe has been set to &d%exp%&7!"
  set-exp-sender: "&8» &7Set exp of %target%'s pickaxe to &d%exp%&7!"

# Progress bar for lore pickaxe
progress:
  not-completed: "&d"
  completed: "&5"
  bars: 20
  char: '|'

pickaxe:
  name: "&d&lLevel Pickaxe &7%level% [%progress%&7]"
  lore:
    - ''
    - '&d&lStatistics'
    - '&d▎ &fBlocks Mined: &d%blocks%'
    - '&d▎ &fPickaxe Exp: &d%exp%/%exp_required%'
    - '&d▎ &fPickaxe Level: &d%level% &7[%progress%&7]'
    - ''
    - '&c&lEnchantments'
    - '&c▎ %Enchant-1%'
    - '&c▎ %Enchant-2%'
    - '&c▎ %Enchant-3%'
    - '&c▎ %Enchant-4%'
    - '&c▎ %Enchant-5%'
    - '&c▎ %Enchant-6%'
    - '&c▎ %Enchant-7%'
    - '&c▎ %Enchant-8%'
    - '&c▎ %Enchant-9%'
    - '&c▎ %Enchant-10%'
    - '&c▎ %Enchant-11%'
    - '&c▎ %Enchant-12%'
    - '&c▎ %Enchant-13%'
    - '&c▎ %Enchant-14%'
    - '&c▎ %Enchant-15%'

# Exp per block
blocks:
  STONE: 10

# Pickaxe Levels
levels:
  1:
    enchants:
      - efficiency ; 1
      - fortune ; 1
  2:
    exp: 10
    enchants:
      - efficiency ; 2
      - fortune ; 1
    rewards:
      - "give %player% stone"
  3:
    exp: 25
    enchants:
      - efficiency ; 3
      - fortune ; 1
    rewards:
      - "give %player% emerald"
  4:
    exp: 50
    enchants:
      - efficiency ; 4
      - fortune ; 1
    rewards:
      - "give %player% emerald"
  5:
    exp: 75
    enchants:
      - efficiency ; 5
      - fortune ; 1
    rewards:
      - "give %player% emerald"
  6:
    exp: 100
    enchants:
      - efficiency ; 6
      - fortune ; 1
    rewards:
      - "give %player% stone"
  7:
    exp: 150
    enchants:
      - efficiency ; 7
      - fortune ; 1
    rewards:
      - "give %player% emerald"
  8:
    exp: 250
    enchants:
      - efficiency ; 8
      - fortune ; 1
    rewards:
      - "give %player% emerald"
  9:
    exp: 500
    enchants:
      - efficiency ; 9
      - fortune ; 1
    rewards:
      - "give %player% emerald"
  10:
    exp: 1000
    enchants:
      - efficiency ; 10
      - fortune ; 1
    rewards:
      - "give %player% emerald"