messages:
  invalid-permission: "&cInvalid permissions!"
  invalid-sender: "&cYou cannot execute this command via the console!"
  invalid-target: "&cPlayer &l%player% &cnot found!"
  invalid-number: "&c&l%arg% &cis not a valid number!"
  incuffient-funds: "&cYou do not have enough tokens!"
  usage:
    - ""
    - ""
    - ""
    - ""
  set-gems-usage: "&cUsage: /gems set <player> <amount>"
  add-gems-usage: "&cUsage: /gems add <player> <amount>"
  remove-gems-usage: "&cUsage: /gems remove <player> <amount>"
  give-gems-usage: "&cUsage: /gems give <player> <amount>"
  gems: "&7You currently have &d%gems% &7gems!"
  set-gems: "&7Your gems have been set to &d%gems%&7!"
  set-gems-sender: "&7Set gems of %target% to &d%gems%&7!"
  add-gems: "&d%gems% &7gems have been added to your account!"
  add-gems-sender: "&7Added &d%gems%&7 to the account of %target%!"
  remove-gems: "&d%gems% &7gems have been removed to your account!"
  remove-gems-sender: "&7Removed &d%gems% &7gems from the account of %target%!"
  give-gems: "&7You have given %target% &d%gems% &7gems!"
  receive-gems: "&7You have received &d%gems% &7gems from %sender%!"