# Database settings
database:
  host: "95.217.194.15"
  port: 27017

# General pickaxe menu settings
pickaxe-menu:
  name: "&d&lUpgrade menu"
  slots: 45
  filler:
    name: " "
    lore:
      - " "
    material: "GRAY_STAINED_GLASS_PANE"

# Pickaxe menu enchantment settings
enchants:
  autoblock:
    refundable: true
    name: "&a&lAutoBlock"
    lore:
      - "&7Automatically creates"
      - "&7blocks from ingots."
      - ""
      - "&aCurrent state:"
      - "&7%state%"
      - ""
      - "&aPrice: &7250 gems"
      - ""
      - "&c&lNote: &r&cyou must have the"
      - "&cAutoSmelt enchantment in order"
      - "&cfor this enchantment to work."
    slot: 21
    material: IRON_BLOCK
    chance: 0.005
    price: 10
    increase: 5
    max-level: 100
  autodeposit:
    refundable: true
    name: "&e&lAutoDeposit"
    lore:
      - ""
      - "&7Automatically deposits"
      - "&7your gems into"
      - "&7your bank account."
      - ""
      - "&eCurrent state: "
      - "&7%state%"
      - ""
      - "&c&lNote: &r&cyou must have the"
      - "&cGemChance enchantment in order"
      - "&cfor this enchantment to work."
    slot: 13
    material: HOPPER_MINECART
    chance: 0.005
    price: 10
    increase: 5
    max-level: 100
  autominer:
    refundable: true
    name: "&a&lAutoMiner"
    lore:
      - "&7Automatically makes you money"
      - "&7with the fortune level on your pickaxe."
      - "&7Go to /warp autominer to start!"
      - ""
      - "&aCurrent state:"
      - "&7%state%"
      - ""
      - "&aPrice: &71000 gems"
    slot: 40
    material: STONECUTTER
    chance: 0.005
    price: 10
    increase: 5
    max-level: 100
  autosell:
    refundable: true
    name: "&a&lAutoSell"
    lore:
      - "&7Automatically sells"
      - "&7your inventory when"
      - "&7it's full."
      - ""
      - "&aCurrent state:"
      - "&7%state%"
      - ""
      - "&aPrice: &7500 gems"
    slot: 24
    material: PAPER
    chance: 0.005
    price: 10
    increase: 5
    max-level: 1
  autosmelt:
    refundable: true
    name: "&9&lAutoSmelt"
    lore:
      - "&7Automatically smelts"
      - "&7ores into ingots."
      - ""
      - "&9Current state:"
      - "&7%state%"
      - ""
      - "&9Price: &7150 gems"
    slot: 23
    material: BLAST_FURNACE
    chance: 0.005
    price: 10
    increase: 5
    max-level: 1
  explosive:
    refundable: true
    name: "&c&lExplosive"
    lore:
      - "&7Gives a chance of"
      - "&7creating an explosion at"
      - "&7the broken block."
      - ""
      - "&cCurrent level:"
      - "&7%level%"
      - ""
      - "&cCurrent chance: "
      - "&7%chance%%"
      - ""
      - "&cPrice: &7%price%"
    slot: 31
    material: TNT
    chance: 0.005
    price: 10
    increase: 5
    max-level: 100
  flight:
    refundable: true
    name: "&b&lFlight"
    lore:
      - "&7Gives infinite"
      - "&7flight while holding"
      - "&7your pickaxe."
      - ""
      - "&bCurrent state:"
      - "&7%state%"
      - ""
      - "&bPrice: &7250 gems"
    slot: 32
    material: ELYTRA
    chance: 0.005
    price: 10
    increase: 5
    max-level: 1
  gemchance:
    refundable: true
    name: "&d&lGemChance"
    lore:
      - "&7Increases the chance"
      - "&7of receiving a Gem while"
      - "&7mining."
      - ""
      - "&dCurrent level:"
      - "&7%level%"
      - ""
      - "&dCurrent chance: "
      - "&7%chance%%"
      - ""
      - "&dPrice: &7%price%"
    slot: 22
    material: SUNFLOWER
    chance: 0.005
    price: 10
    increase: 5
    max-level: 100
  haste:
    refundable: true
    name: "Haste"
    lore:
      - "lore1"
      - "lore2"
    slot: 0
    material: GOLDEN_PICKAXE
    chance: 0.005
    price: 10
    increase: 5
    max-level: 2
  jackhammer:
    refundable: true
    name: "&b&lJackHammer"
    lore:
      - "&7Gives a small chance to"
      - "&7remove a complete horizontal layer"
      - "&7from a mine."
      - " "
      - "&bCurrent level: "
      - "&7%level%"
      - " "
      - "&bCurrent chance: "
      - "&7%chance%%"
      - " "
    slot: 12
    material: DIAMOND_PICKAXE
    chance: 0.005
    price: 10
    increase: 5
    max-level: 100
  jump:
    refundable: true
    name: "Jump"
    lore:
      - "lore1"
      - "lore2"
    slot: 1
    material: RABBIT_FOOT
    chance: 0.005
    price: 10
    increase: 5
    max-level: 100
  keyfinder:
    refundable: true
    name: "&d&lKeyfinder"
    lore:
      - "&7Increases the chance"
      - "&7of receiving a crate key"
      - "&7while mining."
      - ""
      - "&dCurrent level:"
      - "&7%level%"
      - ""
      - "&dCurrent chance: "
      - "&7%chance%%"
      - ""
      - "&dPrice: &7%price%"
    slot: 14
    material: TRIPWIRE_HOOK
    chance: 0.005
    price: 10
    increase: 5
    max-level: 100
  laser:
    refundable: true
    name: "&6&lLaser"
    lore:
      - "&7Gives a small chance to"
      - "&7remove a complete vertical layer"
      - "&7from a mine."
      - ""
      - "&6Current level: "
      - "&7%level%"
      - ""
      - "&6Current chance: "
      - "&7%chance%%"
      - ""
      - "&6Price: &7%price%"
    slot: 4
    material: BLAZE_ROD
    chance: 0.005
    price: 10
    increase: 5
    max-level: 100
  lightning:
    refundable: true
    name: "Lightning"
    lore:
      - "lore1"
      - "lore2"
    slot: 2
    material: BONE
    chance: 0.005
    price: 10
    increase: 5
    max-level: 100
  speed:
    refundable: true
    name: "&9&lWalking Speed"
    lore:
      - "&7Gives infinite"
      - "&7walking speed while"
      - "&7holding your pickaxe."
      - ""
      - "&9Current percentage:"
      - "&7%percentage%"
      - ""
      - "&9Price: &7%price%"
    slot: 30
    material: FEATHER
    chance: 0.005
    price: 10
    increase: 5
    max-level: 10

messages:
#  General
  invalid-permission: "&cInvalid permissions!"
  invalid-sender: "&cYou cannot execute this command via the console!"
  invalid-target: "&cPlayer &l%player% &cnot found!"
  invalid-number: "&c&l%arg% &cis not a valid number!"
  incuffient-funds: "&cYou do not have enough tokens!"

#  Usage
  gems-usage:
    - "&e&l------------- &dLevel &ePickaxe &dUsage &e&l-------------"
    - "&7/gems"
    - "&7/gems add <player> <gems>"
    - "&7/gems give <player> <gems>"
    - "&7/gems remove <player> <gems>"
    - "&7/gems set <player> <gems>"
  pickaxe-usage:
    - "&e&l------------- &bGems &bUsage &e&l-------------"
    - "&7/levelpickaxe give <player>"
    - "&7/levelpickaxe setlevel <player> <level>"
    - "&7/levelpickaxe setblocks <player> <blocks>"
    - "&7/levelpickaxe setexp <player> <exp>"
  set-gems-usage: "&cUsage: /gems set <player> <amount>"
  add-gems-usage: "&cUsage: /gems add <player> <amount>"
  remove-gems-usage: "&cUsage: /gems remove <player> <amount>"
  give-gems-usage: "&cUsage: /gems give <player> <amount>"
  give-pickaxe-usage: "&cUsage: /levelpick give <player>"
  set-blocks-usage: "&cUsage: /levelpick setblocks <player> <blocks>"
  set-level-usage: "&cUsage: /levelpick setlevel <player> <level>"
  set-exp-usage: "&cUsage: /levelpick setexp <player> <level>"

#  Gems
  gems: "&7You currently have &d%gems% &7gems!"
  set-gems: "&7Your gems have been set to &d%gems%&7!"
  set-gems-sender: "&7Set gems of %target% to &d%gems%&7!"
  add-gems: "&d%gems% &7gems have been added to your account!"
  add-gems-sender: "&7Added &d%gems%&7 to the account of %target%!"
  remove-gems: "&d%gems% &7gems have been removed to your account!"
  remove-gems-sender: "&7Removed &d%gems% &7gems from the account of %target%!"
  give-gems: "&7You have given %target% &d%gems% &7gems!"
  receive-gems: "&7You have received &d%gems% &7gems from %sender%!"

#  Pickaxe
  give-pickaxe: "&7You have given %target% a level pickaxe!"
  receive-pickaxe: "&7You have received a level pickaxe!"
  reset-pickaxe: "&7Your level pickaxe has been reset!"
  reset-pickaxe-sender: "&7You have reset %target%'s level pickaxe!"
  set-level: "&7The level of your pickaxe has been set to &d%level%&7!"
  set-level-sender: "&7Set level of %target%'s pickaxe to &d%level%&7!"
  set-blocks: "&7The amount of broken blocks of your pickaxe has been set to &d%blocks%&7!"
  set-blocks-sender: "&7Set broken blocks of %target%'s pickaxe to &d%blocks%&7!"
  set-exp: "&7The exp of your pickaxe has been set to &d%exp%&7!"
  set-exp-sender: "&7Set exp of %target%'s pickaxe to &d%exp%&7!"

# Progress bar for lore pickaxe
progress:
  not-completed: "&d"
  completed: "&5"
  bars: 20
  char: '|'

pickaxe:
  name: "&d&lLevel Pickaxe &7[%progress%&7]"
  lore:
    - ''
    - '&d&lStatistics'
    - '&d▎ &fBlocks Mined: &d%blocks%'
    - '&d▎ &fPickaxe Exp: &d%exp%/%exp_required%'
    - '&d▎ &fPickaxe Level: &d%level% &7[%progress%&7]'
    - ''
    - '&c&lEnchantments'
    - '&c▎ %Enchant-1%'
    - '&c▎ %Enchant-2%'
    - '&c▎ %Enchant-3%'
    - '&c▎ %Enchant-4%'
    - '&c▎ %Enchant-5%'
    - '&c▎ %Enchant-6%'
    - '&c▎ %Enchant-7%'
    - '&c▎ %Enchant-8%'
    - '&c▎ %Enchant-9%'
    - '&c▎ %Enchant-10%'
    - '&c▎ %Enchant-11%'
    - '&c▎ %Enchant-12%'
    - '&c▎ %Enchant-13%'
    - '&c▎ %Enchant-14%'
    - '&c▎ %Enchant-15%'

# Exp per block
blocks:
  STONE: 10

# Pickaxe Levels
levels:
  2:
    exp: 10
    rewards:
      - "give %player% stone"
  3:
    exp: 25
    rewards:
      - "give %player% emerald"
  4:
    exp: 50
    rewards:
      - "give %player% emerald"
  5:
    exp: 75
    rewards:
      - "give %player% emerald"
  6:
    exp: 100
    rewards:
      - "give %player% stone"
  7:
    exp: 150
    rewards:
      - "give %player% emerald"
  8:
    exp: 250
    rewards:
      - "give %player% emerald"
  9:
    exp: 500
    rewards:
      - "give %player% emerald"
  10:
    exp: 1000
    rewards:
      - "give %player% emerald"