name: SlamCore
version: ${project.version}
main: me.matzhilven.slamcore.SlamCore
api-version: 1.16
depend: [ ProtocolLib, Mines ]
authors: [ MatzHilven ]
commands:
  gems:
    permission: core.gem
  levelpick:
    permission: core.levelpick
    aliases:
      - levelpickaxe
  givebomb:
    permission: core.minebomb
    aliases:
      - gb

permissions:
  core.gem:
    default: op
  core.gem.admin:
    default: op
  core.levelpick:
    default: op
  core.minebomb:
    default: op